# -*- coding: utf-8 -*-
"""Transfer Learning ResNet18 for Mel Spectrograms 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QcYD-bvGrf65q4x3H22wqH7q9FN4F04
"""

!pip uninstall -y torch torchvision sympy
!pip install torch torchvision

import zipfile
import os

# --- CONFIGURATION ---
zip_path = "/content/spectrogram_000001.zip"
output_folder = "/content/abnormal"

# --- STEP 1: Create the output folder ---
os.makedirs(output_folder, exist_ok=True)

# --- STEP 2: Extract only .png files ---
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    for file_info in zip_ref.infolist():
        filename = file_info.filename
        if filename.lower().endswith(".png"):
            zip_ref.extract(file_info, output_folder)

print(f"Extracted all .png files from {os.path.basename(zip_path)} into: {output_folder}")

import os
import shutil
from glob import glob

# Paths
root_dir = "/content"
target_dir = os.path.join(root_dir, "normal")
abnormal_dir = os.path.join(root_dir, "abnormal")

os.makedirs(target_dir, exist_ok=True)

# Find all PNGs anywhere in /content
png_files = glob(os.path.join(root_dir, "**", "*.png"), recursive=True)

# Filter: only include those NOT in /content/abnormal
png_files = [f for f in png_files if not f.startswith(abnormal_dir)]

print(f"Found {len(png_files)} PNG files (excluding abnormal folder).")

moved = 0
for file_path in png_files:
    filename = os.path.basename(file_path)
    new_path = os.path.join(target_dir, filename)

    # Avoid overwriting duplicates
    base, ext = os.path.splitext(filename)
    i = 1
    while os.path.exists(new_path):
        new_path = os.path.join(target_dir, f"{base}_{i}{ext}")
        i += 1

    shutil.move(file_path, new_path)
    moved += 1

print(f"✅ Moved {moved} PNG files into {target_dir}")
print(f"Total now in /content/normal: {len(os.listdir(target_dir))}")

import os
import random
import shutil

def split_dataset(source_dir, target_dir, split_ratio=0.8):
    classes = ['normal', 'abnormal']
    for cls in classes:
        files = os.listdir(os.path.join(source_dir, cls))
        random.shuffle(files)
        split_point = int(len(files) * split_ratio)
        train_files = files[:split_point]
        val_files = files[split_point:]

        for phase, phase_files in [('train', train_files), ('val', val_files)]:
            dest_dir = os.path.join(target_dir, phase, cls)
            os.makedirs(dest_dir, exist_ok=True)
            for f in phase_files:
                shutil.copy(os.path.join(source_dir, cls, f), os.path.join(dest_dir, f))

source_dir = '/content'  # where /content/normal and /content/abnormal exist
target_dir = '/content/dataset'
split_dataset(source_dir, target_dir)

print("Data split complete!")

import os
import copy
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
from torchvision import datasets, models, transforms

from torchvision import transforms,datasets

data_transforms = {
    'train': transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'val': transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

data_dir = 'dataset'

image_datasets = {
    x: datasets.ImageFolder(os.path.join(data_dir, x), data_transforms[x])
    for x in ['train', 'val']
}

image_datasets = {
    x: datasets.ImageFolder(os.path.join(data_dir, x), data_transforms[x])
    for x in ['train', 'val']
}

dataloaders = {
    x: torch.utils.data.DataLoader(image_datasets[x], batch_size=4, shuffle=True, num_workers=4)
    for x in ['train', 'val']
}

dataset_sizes = {x: len(image_datasets[x]) for x in ['train', 'val']}
class_names = image_datasets['train'].classes

print(f"Dataset sizes: {dataset_sizes}")
print(f"Classes: {class_names}")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

model = models.resnet18(pretrained=True)

# Unfreeze last residual block (layer4) + final FC layer
for name, param in model.named_parameters():
    if "layer4" in name or "fc" in name:
        param.requires_grad = True
    else:
        param.requires_grad = False

# Modify the final layer for binary classification
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 2)
model = model.to(device)

# Loss function, optimizer, scheduler
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-4, momentum=0.9)
scheduler = lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

num_epochs = 25
best_val_loss = float('inf')
patience, trigger = 3, 0
best_model_wts = copy.deepcopy(model.state_dict())

for epoch in range(num_epochs):
    print(f'\nEpoch {epoch+1}/{num_epochs}')
    print('-' * 30)

    for phase in ['train', 'val']:
        if phase == 'train':
            model.train()
        else:
            model.eval()

        running_loss = 0.0
        running_corrects = 0

        for inputs, labels in dataloaders[phase]:
            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            with torch.set_grad_enabled(phase == 'train'):
                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                if phase == 'train':
                    loss.backward()
                    optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        epoch_loss = running_loss / dataset_sizes[phase]
        epoch_acc = running_corrects.double() / dataset_sizes[phase]

        print(f'{phase} Loss: {epoch_loss:.4f} | Acc: {epoch_acc:.4f}')

        # Track validation performance
        if phase == 'val':
            if epoch_loss < best_val_loss:
                best_val_loss = epoch_loss
                best_model_wts = copy.deepcopy(model.state_dict())
                trigger = 0
                print("Validation loss improved, saving best model...")
            else:
                trigger += 1
                print(f"No improvement in val loss for {trigger} epoch(s).")
                if trigger >= patience:
                    print("\n Early stopping triggered, training stopped.")
                    model.load_state_dict(best_model_wts)
                    break

    scheduler.step()
    if trigger >= patience:
        break

save_path = '/content/drive/MyDrive/resnet18_final2.pth'
torch.save(best_model_wts, save_path)
print(f"\n Training complete! Best model saved to: {save_path}")

!mkdir -p /content/drive/MyDrive/
!cp -r /content/dataset /content/drive/MyDrive/

import os

path = '/content/drive/MyDrive/dataset'
for root, dirs, files in os.walk(path):
    print(root)
    for f in files:
        print("  ", f)